SemanticMediaWiki/SemanticInterlanguageLinks

- i18n/en.json
- src/HookRegistry.php
- src/InterlanguageLinksLookup.php
- src/InterlanguageListParserFunction.php
- src/LanguageTargetLinksCache.php
- src/PageContentLanguageModifier.php
- src/PropertyRegistry.php
- src/Search/LanguageResultMatchFinder.php
- tests/phpunit/Unit/InterlanguageLinksLookupTest.php
- tests/phpunit/Unit/LanguageTargetLinksCacheTest.php
- tests/phpunit/Unit/PageContentLanguageModifierTest.php
- tests/phpunit/Unit/Search/LanguageResultMatchFinderTest.php
- tests/phpunit/Unit/Search/SearchResultModifierTest.php
- Move inMemoryPageLanguageCache handling to LanguageTargetLinksCache interface
- Make PropertyRegistry::register non-static
> Tidy, comments

- CHANGELOG.md
- README.md
- SemanticInterlanguageLinks.php
- src/Category/CategoryPageByLanguage.php
- src/Category/CategoryViewerByLanguage.php
- src/HookRegistry.php
- src/InterlanguageLinksLookup.php
- src/LanguageTargetLinksCache.php
- tests/phpunit/Integration/CategoryViewerByLanguageIntegrationTest.php
- tests/phpunit/Unit/Category/CategoryPageByLanguageTest.php
- tests/phpunit/Unit/Category/CategoryViewerByLanguageTest.php
- tests/phpunit/Unit/HookRegistryTest.php
refs #9 to add auto-filtering if `INTERLANGUAGELINK` declares a content language for a category.
> Add CategoryViewerByLanguage, refs #9

- i18n/de.json
* Extend and improve German translations
> I18n German

- i18n/pt-br
> pt-br i18n

- i18n/pt-br.json
- i18n/pt.json
As @kghbln noted here https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/pull/16#issuecomment-69642465
I hope I did it right.
> Now pt.json has all messages translated and pt-br just those different

- .travis.yml
- tests/phpunit/Unit/Category/ByLanguageCategoryViewerTest.php
Caused by https://github.com/wikimedia/mediawiki/commit/8d25d1b1ea18934c88a2fb1a3433348715a42b6b
> MW 1.25 / Fix test for addModuleStyles caused by CategoryViewer

- src/Search/SearchResultModifier.php
- tests/phpunit/Unit/Search/SearchResultModifierTest.php
> Use wfBCP47 to convert a user input, refs #33

- SemanticInterlanguageLinks.php
- src/HookRegistry.php
- tests/phpunit/Unit/HookRegistryTest.php
> Use `SMW::Config::BeforeCompletion`, refs #40

- RELEASE-NOTES.md
- docs/01-parser-function.md
- i18n/SemanticInterlanguageLinks.magic.php
- src/AnnotatedLanguageParserFunction.php
- src/HookRegistry.php
- src/ParserFunctionFactory.php
- tests/phpunit/Unit/AnnotatedLanguageParserFunctionTest.php
- tests/phpunit/Unit/ParserFunctionFactoryTest.php
Returns the `annotatedlanguage` of the current page.
> Add annotatedlanguage parser function

- RELEASE-NOTES.md
- SemanticInterlanguageLinks.php
- composer.json
Refs https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/51:
* Update RELEASE-NOTES.md
* Tiny tweaks 
* Update SemanticInterlanguageLinks.php
* Bump version
* Tiny tweaks
> 1.4.0 release

- SemanticInterlanguageLinks.php
- composer.json
Refs: https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/51
* Update SemanticInterlanguageLinks.php
* Started new development version
* Update composer.json
* Started new development version
> Start new development version

- composer.json
* Bump minimum requirement for Semantic MediaWiki to 2.5+
* Update links
> Update minimum SMW requirement and other tweaks

- README.md
- RELEASE-NOTES.md
- SemanticInterlanguageLinks.php
- composer.json
- docs/02-ask-queries.md
Refs: https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/60
> Release version 1.5.0

- SemanticInterlanguageLinks.php
- composer.json
Refs: https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/issues/60
> Start development of version 2.0.0

- .travis.yml
- SemanticInterlanguageLinks.php
- composer.json
- extension.json
- i18n/en.json
- tests/phpunit/Integration/ParserFunctionIntegrationTest.php
- tests/travis/install-semantic-interlanguage-links.sh
This PR is made in reference to: #66, #67
Fixes #66, Fixes #67
> Add support for `extension.json`

- composer.json
- extension.json
This PR is made in reference to: #68 
- Meta file updates
> Start development of 2.1.0

- .travis.yml
This PR is made in reference to: #
> [CI] Define PHP 7.1 as minimum

- README.md
- RELEASE-NOTES.md
- docs/README.md
- extension.json
This PR is made in reference to: #
- Updated release notes
- Updated documentation
- Updated version number
Fixes #
> Make 2.1.0 release

- extension.json
This PR is made in reference to: #80
- Increment version
Fixes #
> Start 2.2.0 release

- src/HookRegistry.php
> Return Language instead of String

- .github/workflows/main.yml
- .gitignore
- Makefile
- SemanticInterlanguageLinks.php
- composer.json
- extension.json
- tests/bootstrap.php
- tests/phpunit/Unit/Category/LanguageFilterCategoryViewerTest.php
- tests/phpunit/Unit/HookRegistryTest.php
- tests/phpunit/Unit/InterlanguageLinkParserFunctionTest.php
- tests/phpunit/Unit/InterlanguageLinksLookupTest.php
- tests/phpunit/Unit/InterwikiLanguageLinkTest.php
- tests/phpunit/Unit/LanguageLinkAnnotatorTest.php
- tests/phpunit/Unit/LanguageTargetLinksCacheTest.php
- tests/phpunit/Unit/ParserFunctionFactoryTest.php
- A working CI setting for github and local testing
Fixes #90
> Working ci

- src/HookRegistry.php
- src/ParserFunctionFactory.php
- src/Search/MappedSearchResultSet.php
- src/Search/SearchResultModifier.php
- tests/phpunit/Integration/I18nJsonFileIntegrityTest.php
- tests/phpunit/Integration/LanguageFilterCategoryViewerIntegrationTest.php
- tests/phpunit/Integration/ParserFunctionIntegrationTest.php
- tests/phpunit/Unit/HookRegistryTest.php
- tests/phpunit/Unit/InterlanguageLinkParserFunctionTest.php
- tests/phpunit/Unit/InterlanguageLinkTest.php
- tests/phpunit/Unit/InterlanguageListParserFunctionTest.php
- tests/phpunit/Unit/InterwikiLanguageLinkTest.php
- tests/phpunit/Unit/ParserFunctionFactoryTest.php
- tests/phpunit/Unit/Search/MappedSearchResultSetTest.php
- tests/phpunit/Unit/Search/SearchResultModifierTest.php
- tests/phpunit/Unit/SiteLanguageLinkModifierTest.php
- Make more tests work
- 1.36 and 1.37 are problems I am not even thinking about right now.  I poked at them a bit but decided there are other, more pressing problems.
See #86 -- only 6 skipped tests now.
> Tidy tests
